# Generated by Django 4.2.7 on 2024-09-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_rename_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('A1', 'Start'), ('A2', 'Basic'), ('B1', 'Intermediate'), ('B2', 'High Intermediate'), ('C1', 'Advanced'), ('C2', 'Master')], default='A1', max_length=15)),
            ],
        ),
    ]
