# Generated by Django 4.2.7 on 2024-09-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0011_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
    ]
