# Generated by Django 5.1.1 on 2024-09-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0014_alter_language_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('contact', 'Contact'), ('working_hours', 'Working Hours'), ('client', 'Client'), ('coffee', 'Coffee')], max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
